CASES.push({
  id: 'david-sanchez',
  name: 'Caso David Sánchez',
  party: 'psoe',
  phase: 'sentencia',
  year: 2024,
  importe: 's.d.',
  importeNota: 'Plaza presuntamente creada a medida en la Diputación de Badajoz',
  imputados: ['David Sánchez Pérez-Castejón', 'Miguel Ángel Gallardo', '+9 personas (11 acusados en total)'],
  ultima: '2026-06',
  ultimaTexto: 'El juicio queda visto para sentencia el 9 de junio tras 8 sesiones en la Audiencia Provincial de Badajoz (11 acusados, más de 40 testigos). Las defensas piden de forma unánime la absolución; David Sánchez declina su derecho a la última palabra. La acusación popular (PP, Vox y Hazte Oír) pide hasta 6 años para Gallardo. Fallo pendiente.',
  resumen: 'Presunta plaza creada a medida en 2017 para el hermano del presidente del Gobierno como Coordinador de Actividades de los Conservatorios de la Diputación de Badajoz. Imputaciones por prevaricación y tráfico de influencias. La acusación popular unifica a Manos Limpias, Vox, HazteOir, Liberum, Iustitia Europa, Abogados Cristianos y PP.',
  noticias: [
    { fuente: 'The Objective',    titulo: 'Visto para sentencia el juicio a David Sánchez por su contrato en la Diputación de Badajoz',                              fecha: '2026-06-09', url: 'https://theobjective.com/espana/tribunales/2026-06-09/visto-para-sentencia-el-juicio-a-david-sanchez-por-su-contrato-en-la-diputacion-de-badajoz/' },
    { fuente: 'elDiario.es',      titulo: 'El juicio a David Sánchez, visto para sentencia con el alegato final de la defensa: "La acusación es una leyenda"', fecha: '2026-06-09', url: 'https://www.eldiario.es/extremadura/politica/juicio-david-sanchez-visto-sentencia-alegato-final-defensa-acusacion-leyenda_1_13286244.html' },
    { fuente: 'El Independiente', titulo: 'El hermano de Pedro Sánchez se enfrenta a tres años de cárcel: arranca esta semana el juicio en la Audiencia de Badajoz', fecha: '2026-05-24', url: 'https://www.elindependiente.com/espana/2026/05/24/hermano-pedro-sanchez-tres-anos-carcel/' },
    { fuente: 'Moncloa.com',      titulo: 'La Audiencia de Badajoz busca el domicilio de David Sánchez para citarlo a juicio',                                       fecha: '2026-02-17', url: 'https://www.moncloa.com/2026/02/17/audiencia-david-sanchez-juicio-3361358/' },
    { fuente: 'Moncloa.com',      titulo: 'Caso David Sánchez: al tribunal se le pierden ahora 5 testigos',                                                           fecha: '2026-03-04', url: 'https://www.moncloa.com/2026/03/04/david-sanchez-acusados-testigos-3363950/' },
  ],
});