CASES.push({
  id: 'hidrocarburos',
  name: 'Caso Villafuel / Hidrocarburos',
  party: 'trans',
  phase: 'instruccion',
  year: 2024,
  importe: '€231 M',
  importeNota: 'Fraude estimado de IVA en hidrocarburos (revisado al alza)',
  imputados: ['Víctor de Aldama', 'Claudio Rivas', 'Carmen Pano', 'Leonor González Pano', 'red de empresarios y testaferros'],
  ultima: '2026-06',
  ultimaTexto: 'Pedraz prorroga la instrucción seis meses más, hasta diciembre de 2026, y el 15-jun propone juzgar al socio de Aldama, Claudio Rivas, y a un capitán de la Guardia Civil por un fraude de 148 M en una de las piezas. La UCO cifra el fraude global en 231 M y vincula la trama con el caso Zapatero.',
  resumen: 'Trama de fraude del IVA en hidrocarburos con epicentro en la empresa Villafuel (propiedad de Claudio Rivas), que obtuvo en 2022 la licencia de operador mayorista pese a no cumplir requisitos. La UCO sitúa pagos a Koldo y a Ábalos, y vincula al entorno político del PSOE. Investigación bajo el juez Santiago Pedraz (AN, JCI nº 5). Pieza separada conectada al caso Koldo y al caso Zapatero.',
  noticias: [
    { fuente: 'Infobae',      titulo: 'Pedraz propone juzgar al socio de Aldama y a un capitán de la Guardia Civil por un fraude de 148 M en el IVA de los hidrocarburos', fecha: '2026-06-15', url: 'https://www.infobae.com/espana/2026/06/15/el-juez-pedraz-propone-juzgar-al-socio-de-aldama-y-a-un-capitan-de-la-guardia-civil-por-un-fraude-de-148-millones-en-el-iva-de-los-hidrocarburos/' },
    { fuente: 'The Objective', titulo: 'Pedraz prorroga hasta diciembre la causa del fraude de hidrocarburos que afecta a Aldama',                   fecha: '2026-06-08', url: 'https://theobjective.com/espana/tribunales/2026-06-08/pedraz-diciembre-fraude-hidrocarburos-aldama/' },
    { fuente: 'El Debate',     titulo: 'Caso hidrocarburos: el fraude millonario que conecta a Aldama, Koldo y Ábalos y llega hasta Zapatero',     fecha: '2026-05-18', url: 'https://www.eldebate.com/espana/20260518/caso-hidrocarburos-fraude-millonario-conecta-aldama-koldo-abalos-llega-hasta-zapatero_416378.html' },
    { fuente: 'Deia',          titulo: 'Aldama y su socio Rivas, ante el juez por fraude millonario en el IVA de hidrocarburos',                    fecha: '2026-01-25', url: 'https://www.deia.eus/politica/2026/01/25/aldama-socio-rivas-juez-fraude-millonario-iva-hidrocarburos-10615428.html' },
    { fuente: 'Wikipedia',     titulo: 'Trama de los hidrocarburos (resumen y cronología)',                                                          fecha: '2026-03-03', url: 'https://es.wikipedia.org/wiki/Trama_de_los_hidrocarburos' },
  ],
});
