CASES.push({
  id: 'punica',
  name: 'Caso Púnica',
  party: 'pp',
  phase: 'intermedia',
  year: 2014,
  importe: '€250 M',
  importeNota: 'Adjudicaciones irregulares y mordidas en municipios de Madrid',
  imputados: ['Francisco Granados', 'David Marjaliza', 'Javier López Madrid', '+100 imputados en 14 piezas'],
  ultima: '2026-05',
  ultimaTexto: 'La AN abre juicio oral contra Granados y otras 40 personas y 79 empresas en la pieza 8 (adjudicaciones de suelo público y transportes en la CAM). Segundo juicio (fiestas populares) celebrado entre enero y marzo de 2026.',
  resumen: 'Macrocausa de financiación irregular y mordidas en adjudicaciones de ayuntamientos del PP en Madrid, Murcia, León y Valencia, fragmentada en 14 piezas separadas. Granados es el principal acusado, con prisión preventiva 2014-2017. Las piezas siguen llegando a juicio una a una.',
  piezas: [
    { nombre: 'Pieza Eficiencia energética (Cofely)', estado: 'sentencia', nota: 'Sobornos por contratos de eficiencia energética adjudicados a Cofely en ayuntamientos de Madrid (2012–2014); la AN condenó a 29 personas a hasta 8 años en dic 2025 (seis exalcaldes entre ellos)' },
    { nombre: 'Pieza Fiestas de municipios de Madrid', estado: 'sentencia', nota: 'Amaño de contratos de fiestas en municipios del PP (2004–2013); segundo juicio oral del 19-ene al 5-mar 2026; Fiscalía pide 6 años a Granados; fallo pendiente' },
    { nombre: 'Pieza Urbanismo Valdemoro', estado: 'intermedia', nota: 'Instrucción cerrada; pendiente de informe pericial' },
    { nombre: 'Pieza Transportes y suelo CAM', estado: 'intermedia', nota: 'Juicio oral abierto may 2026; 40 personas y 79 empresas; Granados principal acusado' },
    { nombre: 'Pieza Reputación online', estado: 'archivo', nota: 'Archivada en 2024; investigaba contratación de trabajos de reputación online de cargos del PP' },
  ],
  noticias: [
    { fuente: 'El Plural',     titulo: 'La Audiencia Nacional abre juicio oral contra Granados y otras 40 personas por corrupción en una pieza separada de Púnica', fecha: '2026-05-26', url: 'https://www.elplural.com/sociedad/tribunales/audiencia-nacional-abre-juicio-oral-contra-granados-40-personas-corrupcion-pieza-separada-punica_391157102' },
    { fuente: 'Infobae',       titulo: 'La AN condena a 29 personas en el mayor pelotazo de Púnica (pieza 6, eficiencia energética): seis exalcaldes entre los condenados', fecha: '2025-12-22', url: 'https://www.infobae.com/espana/2025/12/22/la-audiencia-nacional-dicta-sentencia-contra-29-personas-en-el-mayor-pelotazo-de-la-trama-punica-condena-a-cinco-exalcaldes-del-pp-uno-del-psoe-y-otro-de-un-partido-local/' },
    { fuente: 'El Debate',     titulo: 'Granados regresará al banquillo en enero de 2026 para su segundo juicio del caso Púnica',                                    fecha: '2025-12-20', url: 'https://www.eldebate.com/espana/20251220/granados-regresara-banquillo-enero-2026-segundo-juicio-caso-punica_367449.html' },
  ],
});
